### PR TITLE
Fix: Choose the correct user to display as the chatting partner in the inbox

### LINKED ISSUE #819: Bug: Inbox is showing your own profile in the preview of a private chat with someone else
**Describe the bug**
The inbox shows previews of your chats with other people. For private chats, the preview should usually contain the profile image and name of the person you're chatting to. Instead, if the last message was your own your own profile image and name will be shown.

**To Reproduce**
- Start a private chat with somebody else
- Make sure the last message in the chat was written by yourself
- Go to your inbox - your own profile picture and name will be shown rather than the other person's

**Expected behavior**
The profile picture and name of the person you're chatting with should always be shown in the chat previews

**Screenshots**
Screenshot from 2021-12-12 20-37-45

### PR DESCRIPTION
**Pull request by verena-e-p**
Closes #819

### CODE REVIEW

File: frontend/pages/inbox.js [hunk 1]
```diff
@@ -263,12 +263,12 @@ export default function Inbox({ chatData, next }) {
...
 }
 
-const parseChats = (chats, user, texts) =>
+const parseChats = (chats, texts) =>
   chats
     ? chats.map((chat) => ({
         ...chat,
         chatting_partner:
-          chat.participants.length === 2 && chat.participants.filter((p) => p.id != user?.id)[0],
+          chat.participants.length === 2 && chat.participants.find((p) => p.id !== chat.user.id),
```
Comment (positiveimpact) [inline frontend/pages/inbox.js:271]: Nice refactor!

**Review by positiveimpact — APPROVED** [review]
LGTM! Great fix :)
