### PR TITLE
Fix: Check translations layout for small screens

### LINKED ISSUE #1087: Bug: The translate page is a mess on mobile
**Describe the bug**
On small screens the page to check the translations of your project/organization is basically unusable.

**To Reproduce**
Click "Check translations" while editing a project or organization

**Expected behavior**
Elements should be below each other rather than next to each other on mobile

**Screenshots**
Screenshot from 2022-10-10 11-31-58

### PR DESCRIPTION
**Pull request by JoshKornfeld**
## Description

Closes #1087 

- Changes to screen sizes <960px include: Fields are in columns, surrounded by a border, top buttons for going back, auto translating & saving are now a fixed appbar with icons. The icon, when hovered will display a tooltip indicating its function.
- Added a maximum character length to certain fields, with a tracker of how many characters are used (projects, users , orgs)
- Added a title to user's profile check translations page for bio changing 
- Added some space between project description and its help text

## Test plan

1. Check translations while editing project/org/profile 
2. 2 different screens for <960px and >=960px width

## Before landing

1. PR has meaningful title
1. `yarn lint` passes (frontend)
1. `yarn format` passes (frontend)
1. `make format` passes (backend)

### CODE REVIEW

File: frontend/pages/createorganization.js [hunk 1]
```diff
@@ -344,6 +344,8 @@ export default function CreateOrganization({ tagOptions, rolesOptions, allHubs }
         textKey: "info.short_description",
         rows: 5,
         headlineTextKey: "short_description",
+        maxCharacters: 280,
```
Comment (positiveimpact) [inline frontend/pages/createorganization.js:347]: I'd allow a bit more characters for the translation, maybe 350 because some languages make the text longer

**Review by positiveimpact — APPROVED** [review]
LGTM other than my comment!
