### PR TITLE
Fixed: YouTube link can't be cut off anymore when truncating project description

### LINKED ISSUE #506: Links to youtube videos should never be cut off by the show more/less functionality of the project description
YouTube video links in project descriptions will be rendered as embedded Youtube videos usually. However, if a YouTube video link is exactly at the cutoff point of the project description (which is only shown when clicking on "show more") the video will not be embedded and the link will not work.
Therefore a link should never be cut off when truncating the project description.

Example for a failing project description: 
`If you want to include1If you want to include2If you want to include3If you want to include4If you want to include5If you want to include6If you want to include7If you want to include8If you want to include9If you want to include10If you want to include11If you want to include12If you want to include13If you want to include14If you want to include15If you want to include16 https://www.youtube.com/watch?v=Rvr65dGBMqw`

### PR DESCRIPTION
**Pull request by verena-e-p**
* The index to cut off the project description for the show more / show less functionality is now calculated to avoid cutting in between YouTube links. ( Closes #506 )

* Also ran `yarn lint` and `yarn format`

## Before landing

1. PR has meaningful title
1. `yarn lint` passes
1. `yarn format` passes

### CODE REVIEW

File: frontend/src/components/donation/donorForest/DonorForestEntry.js [hunk 1]
```diff
@@ -27,21 +27,20 @@ const useStyles = makeStyles((theme) => ({
 
 const getWidthFromStep = (step) => {
   const widths = {
-    "1": "65px",
```
Comment (verena-e-p) [inline frontend/src/components/donation/donorForest/DonorForestEntry.js:30]: `yarn format` got rid of these quotation marks. Just want to make sure they were not necessary in this case.

Comment (positiveimpact) [reply frontend/src/components/donation/donorForest/DonorForestEntry.js:30]: I think you test that you'd have to add a donation by a user and check if the /donorforest page works as expected

**Review by positiveimpact — APPROVED** [review]
LGTM! :)
